dist: xenial
language: rust
services: docker
sudo: required

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

env:
  global:
    - CRATE_NAME=redis-nativemsgpack

matrix:
  include:
    # stable
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: stable
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: stable

    # nightly
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

before_script:
  - rustc -V
  - cargo -V
  - cargo install --force cross
  - git --version
  - echo $TRAVIS_BRANCH
  - git checkout $TRAVIS_BRANCH
  - git rev-parse HEAD

script:
  - cross build --target $TARGET
  - cargo test --verbose

before_deploy:
  - bash ci/before_deploy.sh

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

deploy:
  provider: releases
  api_key:
    secure: go4ipJgn97LQSUsWkhF/p2stGRZ/TskmWb0i03E8YoepsnW0DdDo+cLenbIKslLKv5M0P3KHdMIgsF+i2oGS9ILG46k2EIWyL8SaLkD2bNKH2ptgCGZkgMQfkeIDhK8AEQbpf2R74jIonWXC5DXybaFQ9gkWz+4pBZdWs7+m4UKtcqTOkkpWrC80rciViG1s9v/Rft/IBuyigoFWh8e3xsS/yXjxMxijauyA9IbOnrZyy1acTt2/s5zzvhJUk/LN74Z11i4k2qKm3REdjqK/8Y8+XgBvGD27jzucdEEb64FGvKutixhsMh+LJm1BhMmU4ow0n+KYlbxoezaNMdSX2qquZMP03gpI/aJL8M5jiahgHEfDOTZe5RDml0ETrF0lo0YiC6wj64RKuSfYCf4s/fr34mjWYJwQJ7KZKJ/62iV4bdUErRz31amDwNlZIYnBxMKjWw1y927uwicQuvygEEd07H2jaVi8KX+lhSykFDP86otpQEZ0Go+2cLXnxt6yKmBjSpR/BQy8wWVKHYXKRFtQe9bk8bysRamefGFaaASymY7sjkBHiqQFmh2tcwKX8cYF5j71al1e5X4Y0THVt1N5k86idcQzm19noIBBNT3dx8xds4qiPPD5E33sF1GsgM3JB+WR7ZqBcGWrP9i10M1ts/IiS7lGWAWNHaxL0e0=
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.tar.gz
  skip_cleanup: true
  on:
    repo: ocadaruma/redis-nativemsgpack
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
